### ISSUE TITLE
Python 3.10

### ISSUE THREAD

**Issue by gilesknap** [conqp/rcon#12]
Is it possible to support Python 3.9?

https://github.com/conqp/rcon/blob/master/setup.py#L12

The restriction to 3.10 is breaking github CI for mcwb as the default runner does not have 3.10 installed. I could fix that but its also hard for users of WSL2 on windows to get hold of a Python3.10. I'm trying to make simple instructions for novice users to make use of this library and would like to avoid describing deadsnakes PPA !

Thanks.

**Comment by conqp** [comment]
I updated the version contraint because I use [PEP 604](https://peps.python.org/pep-0604/), which was introduced in Python 3.10.

**Comment by gilesknap** [comment]
OK, I'm all for progress so I'll just fix mciwb's dependencies and docs :-)

Thanks.
