### ISSUE TITLE
rconshell does not notice server going away

### ISSUE THREAD

**Issue by miiichael** [conqp/rcon#16]
Probably applies to the other clients too. Steps to reproduce:
- connect to any Minecraft server with rconshell
- stop the server (eg. by sending a `stop` command)
- wait for server to stop
- note that rconshell does not notice that the connection to server is now in CLOSE_WAIT state (until you try to send a command)

Expected behaviour:
- rconshell to exit or complain when the connection to the server is closed

rcon 2.3.6 from Debian.

**Comment by conqp** [comment]
For that to happen, the RCON shell would need to constantly need to check the connection i.e. via a keepalive packet, which RCON does not support.

**Comment by miiichael** [comment]
No, keepalive packets are not necessary here; if the server closes the connection, clients should be able to notice straight away.

Whoops, I wrote my own RCON client. :sweat_smile: 
[mini-rcon-cli.txt](https://github.com/conqp/rcon/files/10423211/mini-rcon-cli.txt)
