### ISSUE TITLE
Rcon not work

### ISSUE THREAD

**Issue by Thomas-R-dev** [conqp/rcon#18]
Hello , i test examples and no one works.

**Comment by Juksefantomet** [comment]
Hello, i had the same issue.

i had to change from single quotes to double quotes to get my game to respond to the rcon commmands 😄 give it a go and see if that was your issue as well.

**Comment by Thomas-R-dev** [comment]
> Hello, i had the same issue.
> 
> i had to change from single quotes to double quotes to get my game to respond to the rcon commmands 😄 give it a go and see if that was your issue as well.

My code :

```py
from rcon.source import rcon

print("Connecting to server...")
async def main():
    response = await rcon("status", host="192.168.1.25", port=28018, passwd=password)
    print(response)

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

Help please :(

**Comment by Juksefantomet** [comment]
You need to add more details about what you are trying to rcon towards, that is only the rcon script, but no context as to what server you are attempting to execute the command towards and what is happening.

**Comment by Thomas-R-dev** [comment]
i try to send "status" on server ...

**Comment by Juksefantomet** [comment]
Answer these questions:

1. what game server is running on 192.168.1.25, "status" tells nothing to us as a third party what is even expected as a command from that game, e.g. some games requires / commands prior to the original command
2. Are you using rcon from the same machine (192.168.1.25)
3. What error or output do you get, when you run the script what does the terminal print?

If you do not provide any answers to these questions, no help will arrive

**Comment by Thomas-R-dev** [comment]
1. Rust
2. Yes
3. No error , no response , nothing

is it good ?

**Comment by Juksefantomet** [comment]
validate your dedicated server config for Rust:

https://developer.valvesoftware.com/wiki/Rust_Dedicated_Server

ensure everything is working as expected, if you can use a premade rcon software like rustadmin which is mentioned in that guide you can confirm rcon is actually set up correctly before you implement your own custom script.

i would additionally suggest trying a different port, 27018 is often used in a range of connection ports for clients and if that is a reserved port used by rust for handling client connection that will prevent rcon for functioning as expected 😄 

good luck!

**Comment by Thomas-R-dev** [comment]
> 
![Capture d’écran 2023-07-25 142517](https://github.com/conqp/rcon/assets/20694389/7379101f-8d2f-4f8a-a1b9-1160dae1d7ad)

Thanks , i miss something ?

**Comment by Juksefantomet** [comment]
I can't answer that 😄 

But i can point out that i see you're running the server on windows. Don't forget to check firewall rules and windows defender for ports related to rust / rcon. 

i would recommend trying another port then 27018 as those ports are used by steam for various things, unless that is the recommended rust rcon port.

**Comment by Thomas-R-dev** [comment]
With RustAdmin my server is good...i'm trying to make my own app to automate the update...but i can't connect to my server, so frustrating and no one can find a solution :(

**Comment by Juksefantomet** [comment]
I do not know to what extent you've attempted various connections, but your server has rcon listen ip set to 0.0.0.0 which means "any interface", you can try and change that to match the local ip of the server 192.168.1.25:

```
+rcon.ip 192.168.1.25
```

or you can try and alter your script.

try one of these more rudimentary approaches

```
from rcon.source import Client

with Client("192.168.1.25", 27018, passwd="password") as client:
    response = client.run('status')

print(response)
```

or

```
from rcon.source import Client

with Client("127.0.0.1", 27018, passwd="password") as client:
    response = client.run('status')

print(response)
```

or

```
from rcon.source import Client

with Client("0.0.0.0", 27018, passwd="password") as client:
    response = client.run('status')

print(response)

```

**Comment by Thomas-R-dev** [comment]
When i use wrong port i have a timeout , with a good port ... no error and command don't work ... it's weird lol

I can't identify the problem xD

**Comment by conqp** [comment]
We're 13 posts into this thread and you still have not posted an actual error message.
Please describe in detail your setup and from which host you're running which program connecting to what host, which Python version you're using and which version of `rcon`.
Also post the exact error messages you receive.
