### ISSUE TITLE
Async timeout support

### ISSUE THREAD

**Issue by durzo** [conqp/rcon#23]
clone of #22 except I would like this ability, thanks.

**Comment by conqp** [comment]
The used [`asyncio.open_connection()`](https://docs.python.org/3/library/asyncio-stream.html) does not appear to support any connection timeout parameter. There's only timeout parameters for SSL handshakes, which RCON does not use.
How do you suppose to implement this?

**Comment by durzo** [comment]
I mean... maybe https://stackoverflow.com/questions/29756507/how-can-i-add-a-connection-timeout-with-asyncio ?

**Comment by conqp** [comment]
Thanks. I also just found it. It's been a while, since I worked with Python ans rsyncio in particular.
Please check out https://github.com/conqp/rcon/commit/6bb56e2fe80d551317881b5eb020f944ab83d49f

**Comment by durzo** [comment]
working fine here. thanks!
