### ISSUE TITLE
How do I use multiple commands?

### ISSUE THREAD

**Issue by yota54123** [conqp/rcon#24]
I can only use the first command. But the command that shows the message "aaaa1"
"aaaa2" doesn't show it.

from rcon.source import Client

host = '127.0.0.1'
port = 25575
password = "admin"

with Client(host, 25575, passwd=password) as client:
    response = client.run('Broadcast aaaa1')
    response2 = client.run('Broadcast aaaa2')

print(response)
print(response2)

**Comment by conqp** [comment]
Please

1. Provide a minimal reproducible example of the code you run, i.e. valid Python code in a code block.
2. The actual output of the program run
3. The expected output of the program
4. The type of server you connect to.

**Comment by conqp** [comment]
I am gling to close this due to lack of feedback.
Feel free to reopen when you have the time to supply sufficient debug info.
