### ISSUE TITLE
SessionTimeout exception on PalWorld

### ISSUE THREAD

**Issue by SalSevenSix** [conqp/rcon#29]
So this rcon client doesn't work with PalWorld. It throws a SessionTimeout exception. Issue is here...
```
    if response.id != request.id:
        raise SessionTimeout()
```
Looks like PalWorld is always returning 0 for the response ID. I think that it's actually PalWorld that needs to be fixed, but thought I should raise the issue to get awareness. I tried 2 different rcon CLI clients and on only 1 worked - https://github.com/gorcon/rcon-cli

**Comment by conqp** [comment]
https://github.com/conqp/rcon/issues/25
