### ISSUE TITLE
Need support for different encoding

### ISSUE THREAD

**Issue by CDboyOne** [conqp/rcon#4]
SRCDS (Source Dedicated Server) uses RCON too, but SRCDS sends different encoding sometimes. In most time it is ASCII, but sometimes it returns UTF-8, or even GB2312 when meeting Chinese characters. For example, 
Extension aoweif.ext.dll failed to load: 找不到指定的模块。
will let SRCDS return GB2312 encoding. Maybe you can use module chardet to detect the encoding.

**Comment by conqp** [comment]
I am reluctant to add dependencies on third party libraries to rcon.
However, I added kwargs to specify an encoding other that UTF-8 on the respective functions in https://github.com/conqp/rcon/commit/d66e8584a5e3e9cb6ff220ac1287652db8747ba2.
Please check it out and report back whether it resolves your issue.

**Comment by CDboyOne** [comment]
I think there are some errors in [d66e858](https://github.com/conqp/rcon/commit/d66e8584a5e3e9cb6ff220ac1287652db8747ba2). `encode()` or `decode()` should be called on Packet Body only, not the whole packet.

Another problem (not error) is that SRCDS returns different encodings on different kinds of packet body content. I think this can be solved by offering two more parameters to `Client.run()`. 
One is `str` that defines the encoding used when making request packet body. 
The other is `Callable[bytes, str]` which decides encoding by the bytes of response packet body.

As far as I know, there is no need to add encoding support to other functions.

**Comment by conqp** [comment]
I don't understand.

1.  Where do you see a problem with a faulty encode or decode?
2.  Only the `payload` will ever be en- and decoded.
3.  In what actual use case do you need different encoding? Please provide the full code and corresponding result.

**Comment by CDboyOne** [comment]
Sorry it is my fault. I tested the commit and it works fine.

And I found that SRCDS may use one single encoding for one specific region. For me, it is GB2312 for China. And GB2312 includes ASCII, which is the default encoding of SRCDS. So offering explicit encoding parameter is enough.

Thanks for the nice update!
